name: Create release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

env:
  tag: ${{ github.ref }}
  file-name: sample-vanilla-${{ tag }}.zip

jobs:
  release:
    name: Release pushed tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: melkypie/resource-packs
          ref: sample-vanilla
          path: sample-vanilla

      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r ${{ file-name }} sample-vanilla

      - name: Upload sample
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          name: Sample/Resource packs ${{ tag }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          overwrite: true
          allowUpdates: true
          file: ${{ sample-vanilla }}
          generateReleaseNotes: true