name: Create Sample Release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  release:
    name: Release pushed tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
        if: ${{ steps.release-label.outputs.level != null }}
        with:
          semver_only: true

      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.3.1
        with:
          myToken: ${{ secrets.ACCESS_TOKEN }}

      - name: Upload sample
        uses: ncipollo/release-action@v1
        with:
          name: Sample/Resource packs ${{ github.ref_name }}
          token: ${{ secrets.ACCESS_TOKEN }}
          allowUpdates: true
          body: ${{ steps.changelog.outputs.changelog }}
